config/routes.rb
Anr::Application.routes.draw do
  resources :pages, :only => :index
  get 'about_us' => 'pages#about', :as => :about_us
  get 'contact' => 'pages#contact', :as => :contact
  get 'dashboard' => 'tournaments#index', :as => :dashboard
  get 'console' => 'organizers#index', :as => :console
  devise_for :organizers, controllers: { registrations: 'organizers/registrations' }
  devise_for :admins, controllers: { registrations: 'admins/registrations' }

  resources :competitors

  resources :schedules, :only => [:new, :edit, :update]

  resources :rounds, :except => [:index, :create, :destroy]

  resources :participants, :only => [:new, :create, :destroy]

  resources :tournaments

  resources :players

  resources :organizers, :only => [:index, :show]

  root :to => 'pages#index'

end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :action, :end, :finished, :number, :schedules_attributes,
                  :scheduling_type, :start, :state, :tournament_id

  belongs_to :tournament
  has_many :schedules, :dependent => :destroy
  has_many :participants, through: :tournament

  accepts_nested_attributes_for :schedules
  validates :tournament_id, :presence => true, :numericality => { :only_integer => true }

  validates_associated :schedules

  def ready
    self.start = nil
    self.state = "Ready"
    self.action = "Start"
    self.save
  end

  def in_progress
    self.start = Time.now
    self.state = "In Progress"
    self.action = "End"
    self.save
  end

  def closed
    self.start = Time.now unless self.start
    self.end = Time.now
    self.state = "Closed"
    self.action = "Post-Round"
    self.save
  end

  def not_scheduled
    self.state = "Not Scheduled"
    self.action = "Schedule"
    self.save
  end

  def ready?
    @isReady ||= (self.state == "Ready")? true : false
  end

  def in_progress?
    @isInProgress ||= (self.state == "In Progress")? true : false
  end

  def not_scheduled?
    @isNotScheduled ||= (self.state == "Not Scheduled")? true : false
  end

  def swiss?
    @isSwiss ||= (self.scheduling_type == "Swiss")? true : false
  end

  def round_robin?
    @isRoundRobin ||= (self.scheduling_type == "Round Robin")? true : false
  end

  def single_elimination?
    @isSingleElimination ||= (self.scheduling_type == "Single Elimination")? true : false
  end

  def update_table
    self.schedules.each do |schedule|
      # initialize data (must not use cache)
      opponent_result = Result.find(schedule.results.first.opponent.results.last.id)
      schedule_id = Result.find(schedule.results.first.id).schedule_id
      result = Result.find(schedule.results.last)
      opponent_schedule_id = Result.find(schedule.results.last.opponent.results.last.id).schedule_id
      # set first result table
      opponent_result.schedule_id = schedule_id
      Round.reset_score_or_bye(opponent_result)
      # set last result table
      result.schedule_id = opponent_schedule_id
      Round.reset_score_or_bye(result)
    end
    round = Round.find(self.id, :include => :schedules)
    round.schedules.each do |schedule|
      if schedule.results.count > 2
        result1 = schedule.results.first
        result2 = Result.find_by_schedule_id_and_participant_id(schedule.results.first.schedule_id, schedule.results.first.opponent_id)
        schedules = Schedule.find_all_by_round_id(round.id)
        schedules.each do |s|
          if s.results.count < 2
            result1.schedule_id = s.id
            Round.reset_score_or_bye(result1)
            result2.schedule_id = s.id
            Round.reset_score_or_bye(result2)
          end
        end
      end
    end
    self.ready
    self
  end

  private

  def self.calculate_round(tournament, trigger)
    tournament.rounds.each do |round|
      round.destroy
    end
    if trigger == "Without" or trigger == "Elimination1"
      count = tournament.participants.count - 2
      round = Math.log2(count).to_i if count > 1
      round = 0 if count < 2
      number = 1
      if trigger == "Without"
        scheduling_type = "Swiss"
        tournament.without
      elsif trigger == "Elimination1"
        scheduling_type = "Single Elimination"
        tournament.elimination1
      end
      Round.create :tournament_id => tournament.id, :scheduling_type => scheduling_type, :state => "Not Scheduled", :action => "Schedule", :number => number unless count < 1
      number = number + 1
      round.times do
        Round.create :tournament_id => tournament.id, :scheduling_type => scheduling_type, :state => "Not Ready", :action => "Pre-Round", :number => number
        number = number + 1
      end
    elsif trigger == "With4" or trigger == "With8"
      count = tournament.participants.count - 2
      round = Math.log2(count).to_i if count > 1
      round = 0 if count < 2
      number = 1
      if trigger == "With4"
        participant_limit = 3
        round_limit = 2
        tournament.with4
      elsif trigger == "With8"
        participant_limit = 7
        round_limit = 3
        tournament.with8
      end
      if count > participant_limit
        Round.create :tournament_id => tournament.id, :scheduling_type => "Swiss", :state => "Not Scheduled", :action => "Schedule", :number => number unless count < 1
        number = number + 1
        (round - round_limit).times do
          Round.create :tournament_id => tournament.id, :scheduling_type => "Swiss", :state => "Not Ready", :action => "Pre-Round", :number => number
          number = number + 1
        end
      end
      if number == 1 and count > 0
        Round.create :tournament_id => tournament.id, :scheduling_type => "Single Elimination", :state => "Not Scheduled", :action => "Schedule", :number => number
        number = number + 1
      end
      round.times do
        Round.create :tournament_id => tournament.id, :scheduling_type => "Single Elimination", :state => "Not Ready", :action => "Pre-Round", :number => number
        number = number + 1
      end
    elsif trigger == "Robin"
      count = tournament.participants.count - 2
      number = 1
      tournament.robin
      Round.create :tournament_id => tournament.id, :scheduling_type => "Round Robin", :state => "Not Scheduled", :action => "Schedule", :number => number unless count < 1
      number = number + 1
      count = count + 1 if (tournament.participants.count - 1).odd?
      (count - 1).times do
        Round.create :tournament_id => tournament.id, :scheduling_type => "Round Robin", :state => "Not Ready", :action => "Pre-Round", :number => number
        number = number + 1
      end
    end
    if count < 1
      tournament.not_started
    else
      tournament.started
    end
    Participant.reset(tournament)
  end

  def self.trigger(round, trigger)
    participant_bye_id = Participant.bye(round.tournament_id).id
    if trigger == "Start"
      round.in_progress
      "Round has started."
    elsif trigger == "End"
      round.schedules.each do |schedule|
        schedule.results.each do |result|
          Participant.update_personal_points(result) unless result.participant_id == participant_bye_id
        end
      end
      Participant.update_opponent_points(round)
      next_round = Round.find_by_tournament_id_and_number(round.tournament_id, round.number + 1)
      next_round.not_scheduled if next_round
      Participant.update_standings(round)
      round.closed
      "Round has ended."
    end
  end

  def self.reset_score_or_bye(result)
    participant_bye_id = Participant.bye(result.tournament_id).id
    result.prestige = nil
    result.corp_game_points = nil
    result.runner_game_points = nil
    result.rating_score = 0.0
    if result.participant_id == participant_bye_id
      result.prestige = 0
      result.corp_game_points = 0
      result.runner_game_points = 0
    elsif result.opponent_id == participant_bye_id
      result.prestige = 6
      result.corp_game_points = 0
      result.runner_game_points = 0
    end
    result.save
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_filter :authenticate_admin_or_organizer!, :only => [:show, :new, :edit, :update]
  # GET /rounds/1
  # GET /rounds/1.json
  def show
    @round = Round.find(params[:id], :include => [:tournament => {:participants => :player}, :schedules => {:results => {:participant => :player}}])
    @tournament = @round.tournament
    redirect_to @tournament, notice: @tournament.state and return if @tournament.closed?
    @participant_bye = Participant.bye(@tournament.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @round }
    end
  end

  # GET /rounds/new
  # GET /rounds/new.json
  def new
    @tournament = Tournament.find(params[:tournament], :include => [:rounds, :participants, :organizer])
    redirect_to @tournament, notice: @tournament.state and return if @tournament.closed?
    redirect_to root_url, notice: 'Action Not Authorized' and return unless admin_signed_in? or @tournament.organizer == current_organizer
    @round = Round.calculate_round(@tournament, params[:trigger])

    respond_to do |format|
      format.html { redirect_to @tournament }
      format.json { render json: @tournament.rounds }
    end
  end

  # GET /rounds/1/edit
  def edit
    @round = Round.find(params[:id], :include => [:schedules, :tournament => :organizer])
    @tournament = @round.tournament
    redirect_to @tournament, notice: @tournament.state and return if @tournament.closed?
    redirect_to root_url, notice: 'Action Not Authorized' and return unless admin_signed_in? or @tournament.organizer == current_organizer
    if params[:trigger] == "Manual" or params[:trigger] == "Modify"
      @schedules = Schedule.calculate_schedule(@round, params[:trigger], "Random") if params[:trigger] == "Manual"
      @schedules = Schedule.find_all_by_round_id(@round.id, :include => :results) if params[:trigger] == "Modify"
      @round = Round.find(params[:id], :include => [:tournament => {:participants => :results}, :schedules => {:results => {:participant => :player}}]) if params[:trigger] == "Manual"
      @participants = Participant.find(:all, :conditions => ["tournament_id = ?", @tournament.id], :include => :player).sort_by(&:name)
      @participants = Participant.find(:all, :conditions => ["tournament_id = ? and player_id != ?", @tournament.id, Var.bye_id], :include => :player).sort_by(&:name) if (@participants.count - 1).even?
    else
      notice = Round.trigger(@round, params[:trigger])
      respond_to do |format|
        format.html { redirect_to @tournament, notice: notice }
        format.json { render json: [@round, @participants] }
      end
    end
  end

  # PUT /rounds/1
  # PUT /rounds/1.json
  def update
    @round = Round.find(params[:id], :include => [:schedules, :tournament => :organizer])
    @tournament = @round.tournament
    redirect_to @tournament, notice: @tournament.state and return if @tournament.closed?
    redirect_to root_url, notice: 'Action Not Authorized' and return unless admin_signed_in? or @tournament.organizer == current_organizer

    respond_to do |format|
      if @round.update_attributes(params[:round])
        @round.update_table
        format.html { redirect_to @tournament, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        @participants = Participant.find(:all, :conditions => ["tournament_id = ?", @tournament.id], :include => :player)
        @participants = Participant.find(:all, :conditions => ["tournament_id = ? and player_id != ?", @tournament.id, Var.bye_id], :include => :player) if (@participants.count - 1).even?
        format.html { render action: "edit" }
        format.json { render json: [@round.errors, @participants], status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/edit.html.erb
<div class="page-header">
  <h1>Manual Schedule</h1>
</div>

<%= form_for @round, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @round.errors.any? %>
    <div class="alert alert-block alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= f.fields_for :schedules do |s| %>
      <div class="row">
      <%= s.hidden_field :table, value: s.object.table %>
        <%= s.fields_for :results do |r| %>
          <div class="span4">
            <div class="control-group">
              <%= r.label :opponent_id, r.object.participant.name + " vs", :class => 'control-label' %>
              <div class="controls">
                <%= r.select(:opponent_id, @participants.reject{|p| p.id == r.object.participant.id}.collect {|p| [p.name, p.id]}, {}, {:"data-participant-id" => r.object.participant.id, :style => "select"}) -%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </fieldset>

  <div class="form-actions">
    <%= f.submit 'Update', :class => 'btn btn-primary', :onclick => "$(body).addClass('loading');" %>
    <%= link_to 'Cancel', @tournament, :class => 'btn' %>
  </div>
<% end %>

<%= link_to 'Auto Schedule', new_schedule_path(:round => @round.id, :trigger => "Schedule"), :class => 'btn btn-primary' %>

app/views/rounds/show.html.erb
<% content_for(:head) do %>
  <style type="text/css">
    #defaultCountdown { width: 960px; height: 270px; margin: auto; }
    #year { color: #fff; font-size: 0pt; }
  </style>
  <script type="text/javascript">
    $(function () {
      var austDay = new Date();
      austDay = new Date(austDay.getFullYear() + 1, 1 - 1, 26);
      $('#defaultCountdown').countdown({until: '<%= params[:timer] %>'});
      $('#year').text(austDay.getFullYear());
    });
  </script>
<% end %>

<div class="page-header">
  <h1>Round <%= @round.number %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Timer:</strong></dt>
  <dd>Refresh to reset</dd>
</dl>

<div id="defaultCountdown"></div>
<span id="year"></span>

<h2>Tournament Standings</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Place</th>
      <th>Player</th>
      <th>Prestiges</th>
      <th>Match points</th>
      <th>Head to Head</th>
      <th>Strength of Schedule</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>

    <% @round.tournament.participants.sort_by(&:place).each do |participant| %>
      <% unless participant == @participant_bye %>
        <tr>
          <td><%= participant.place %></td>
          <td><%= participant.name %></td>
          <td><%= participant.prestiges %></td>
          <td><%= participant.game_points %></td>
          <td><%= participant.head_to_head %></td>
          <td><%= participant.prestige_strength %> (<%= participant.points_strength %>)</td>
          <td><%= (participant.rating + participant.rating_scores).round %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h2>Round Schedule</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Table</th>
      <th>Player 1</th>
      <th>Player 2</th>
    </tr>
  </thead>
  <tbody>

    <% @round.schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.table %></td>
        <% schedule.results.each do |result| %>
          <td><b><%= result.participant.name %></b></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>