config/routes.rb
Anr::Application.routes.draw do
  resources :pages, :only => :index
  get 'about_us' => 'pages#about', :as => :about_us
  get 'contact' => 'pages#contact', :as => :contact
  get 'dashboard' => 'tournaments#index', :as => :dashboard
  get 'console' => 'organizers#index', :as => :console
  devise_for :organizers, controllers: { registrations: 'organizers/registrations' }
  devise_for :admins, controllers: { registrations: 'admins/registrations' }

  resources :competitors

  resources :schedules, :only => [:new, :edit, :update]

  resources :rounds, :except => [:index, :create, :destroy]

  resources :participants, :only => [:new, :create, :destroy]

  resources :tournaments

  resources :players

  resources :organizers, :only => [:index, :show]

  root :to => 'pages#index'

end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable

  attr_accessor :authentication_code

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :active, :authentication_code, :name, :username, :time_zone

  validates :email, :email => true, :length => { :in => 6..140 }
  validates :name, :presence => true, :length => { :in => 2..140 }

  has_many :organizer_services
  has_many :tournaments
  has_many :participants, through: :tournaments
  has_many :rounds, through: :tournaments

  private

  def self.activate_or_create(params_organizer)
    if params_organizer[:email] and not params_organizer[:email].blank?
      organizer = Organizer.find_by_email params_organizer[:email]
      organizer.active = true if organizer
    end
    organizer = Organizer.new(params_organizer) unless organizer
    organizer
  end
end

app/controllers/organizers/registrations_controller.rb
class Organizers::RegistrationsController < Devise::RegistrationsController
  # POST /resource
  def create
    if Rails.env.development? or verify_recaptcha(:model => Organizer.new(params[:organizer]), :timeout => 3)
      organizer = Organizer.find_by_email params[:organizer][:email] if params[:organizer][:email] and not params[:organizer][:email].blank?
      if organizer
        organizer.active = true
        organizer.save
        sign_in :organizer, organizer, :bypass => true
        respond_with organizer, :location => after_update_path_for(organizer)
      else
        super
      end
    else
      build_resource(params[:organizer])
      clean_up_passwords(resource)
      resource.errors.add :authentication_code, "you entered is not valid. Are you human?"
      respond_with resource
    end
  end

  # DELETE /resource
  def destroy
    resource.active = false
    resource.save
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_navigational_format?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  before_filter :authenticate_organizer!, :only => :show
  before_filter :authenticate_admin!, :only => :index
  # GET /organizers
  # GET /organizers.json
  def index
    @organizers = Organizer.paginate(:page => params[:page], :per_page => Var.per_page).order('id DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizers }
    end
  end

  # GET /organizers/1
  # GET /organizers/1.json
  def show
    @pre_tournaments = Tournament.paginate(:conditions => ["organizer_id = ? and state = ?", current_organizer.id.to_s, "Tournament is not started."], :page => params[:pre_page], :per_page => Var.per_page).order('created_at DESC')
    @post_tournaments = Tournament.paginate(:conditions => ["organizer_id = ? and state = ?", current_organizer.id.to_s, "Tournament has started."], :page => params[:post_page], :per_page => Var.per_page).order('created_at DESC')
    @closed_tournaments = Tournament.paginate(:conditions => ["organizer_id = ? and state = ?", current_organizer.id.to_s, "Tournament is closed."], :page => params[:page], :per_page => Var.per_page).order('created_at DESC')
    @tournament = Tournament.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: current_organizer }
    end
  end
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/views/organizers/index.html.erb
<div class="page-header">
  <h1>Organizers Dashboard</h1>
</div>

<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= notice %>
  </div>
<% end %>

<%= will_paginate @organizers %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Time Zone</th>
<!--       <th>Tank Amount</th>
      <th>Tank Limit</th>
      <th>Boost Limit</th> -->
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    
    <% @organizers.each do |organizer| %>
      <tr>
        <td><%= organizer.email %></td>
        <td><%= organizer.name %></td>
        <td><%= organizer.time_zone %></td>
<!--         <td><%#= organizer.boost_tank_current_amount %></td>
        <td><%#= organizer.boost_tank_full_limit %></td>
        <td><%#= organizer.boost_limit_per_tournament %></td> -->
        <td>
          <%#= link_to 'Edit', edit_organizer_path(organizer), :class => 'btn btn-mini' %>
          <%= link_to 'Delete', organizer, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @organizers %>

app/views/organizers/show.html.erb
<div class="page-header">
  <h1>Tournament That You've Organized</h1>
</div>

<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= notice %>
  </div>
<% end %>

<% unless @pre_tournaments.blank? %>

  <h2>Tournament That Haven't Started</h2>

  <%= will_paginate @pre_tournaments, :param_name => 'pre_page' %>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Tournament Name</th>
        <th>Description</th>
        <th>Status</th>
        <th>Scheduling Type</th>
        <th>Multiplier</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>

      <% @pre_tournaments.each do |tournament| %>
        <tr>
          <td><%= link_to tournament.name, tournament %></td>
          <td><%= simple_format(tournament.description) %></td>
          <td><%= tournament.state %></td>
          <td><%= tournament.scheduling_type %></td>
          <td><%= tournament.rating_multiplier * tournament.rating_boost %></td>
          <td>
            <%= link_to 'Edit', edit_tournament_path(tournament), :class => 'btn btn-mini' unless tournament.closed? %>
            <%= link_to 'Delete', tournament, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' unless tournament.closed? %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @pre_tournaments, :param_name => 'pre_page' %>

<% end %>

<% unless @post_tournaments.blank? %>

  <h2>Active Tournament</h2>

  <%= will_paginate @post_tournaments, :param_name => 'post_page' %>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Tournament Name</th>
        <th>Description</th>
        <th>Status</th>
        <th>Multiplier</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>

      <% @post_tournaments.each do |tournament| %>
        <tr>
          <td><%= link_to tournament.name, tournament %></td>
          <td><%= tournament.description %></td>
          <td><%= tournament.state %></td>
          <td><%= tournament.rating_multiplier * tournament.rating_boost %></td>
          <td>
            <%= link_to 'Edit', edit_tournament_path(tournament), :class => 'btn btn-mini' unless tournament.closed? %>
            <%= link_to 'Delete', tournament, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' unless tournament.closed? %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @post_tournaments, :param_name => 'post_page' %>

<% end %>

<% unless @closed_tournaments.blank? %>

  <h2>Tournament Archive</h2>

  <%= will_paginate @closed_tournaments %>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Tournament Name</th>
        <th>Description</th>
        <th>Status</th>
        <th>Multiplier</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>

      <% @closed_tournaments.each do |tournament| %>
        <tr>
          <td><%= link_to tournament.name, tournament %></td>
          <td><%= tournament.description %></td>
          <td><%= tournament.state %></td>
          <td><%= tournament.rating_multiplier * tournament.rating_boost %></td>
          <td>
            <%= link_to 'Edit', edit_tournament_path(tournament), :class => 'btn btn-mini' unless tournament.closed? %>
            <%= link_to 'Delete', tournament, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' unless tournament.closed? %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @closed_tournaments %>

<% end %>

<%= link_to 'Add a New Tournament', '#tournaments_new', :class => 'btn btn-primary', :"data-toggle" => 'modal' %>

<div id="tournaments_new" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="label_tournaments_new" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 id="label_tournaments_new">Add a New Tournament</h3>
  </div>
  <div class="modal-body">
    <%= form_for @tournament, :html => { :class => 'form-horizontal' } do |f| %>
      <% if @tournament.errors.any? %>
        <div class="alert alert-block alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

          <ul>
          <% @tournament.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="control-group clearfix">
        <%= f.label :name, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :name, :autofocus => true, :class => 'text_field' %>
        </div>
      </div>
      <div class="control-group clearfix">
        <%= f.label :description, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_area :description, :class => 'text_area' %>
        </div>
      </div>
  </div>
  <div class="modal-footer">
      <%= link_to 'Close', '#', :class => 'btn', :"data-dismiss" => 'modal', :"aria-hidden" => true %>
      <%= f.submit nil, :class => 'btn btn-primary', :"data-loading-text" => "Creating Tournament...", :onclick => "$(this).button('loading').addClass('disabled');" %>
    <% end %>
  </div>
</div>

<br /><br />