config/routes.rb
Anr::Application.routes.draw do
  resources :pages, :only => :index
  get 'about_us' => 'pages#about', :as => :about_us
  get 'contact' => 'pages#contact', :as => :contact
  get 'dashboard' => 'tournaments#index', :as => :dashboard
  get 'console' => 'organizers#index', :as => :console
  devise_for :organizers, controllers: { registrations: 'organizers/registrations' }
  devise_for :admins, controllers: { registrations: 'admins/registrations' }

  resources :competitors

  resources :schedules, :only => [:new, :edit, :update]

  resources :rounds, :except => [:index, :create, :destroy]

  resources :participants, :only => [:new, :create, :destroy]

  resources :tournaments

  resources :players

  resources :organizers, :only => [:index, :show]

  root :to => 'pages#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable
  include ActiveModel::Validations

  attr_accessor :tournament_id

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :active, :bye_game_points, :bye_prestiges, :country_id,
                  :login, :game_points, :matches, :matches_with_bye, :name,
                  :prestiges, :rating, :tournament_id, :tournaments, :username

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :active, :bye_game_points, :bye_prestiges, :country_id,
                  :login, :game_points, :matches, :matches_with_bye, :name,
                  :prestiges, :rating, :tournaments, :username, :as => :seed

  belongs_to :country
  has_many :competitor_relations
  has_many :competitors, through: :competitor_relations, source: :competitor
  has_many :participants
  has_many :player_services

  validates :email, :email => true, :length => { :in => 6..140 }
  validates :name, :presence => true, :length => { :in => 2..140 }

  after_create :create_participant, :if => :has_participant?

  def self.find_for_database_authentication(conditions={})
    self.where("username = ?", conditions[:email]).limit(1).first ||
    self.where("email = ?", conditions[:email]).limit(1).first
  end

  def self.update_points(tournament)
    participant_bye = Participant.bye(tournament.id)
  	tournament.participants.each do |participant|
      unless participant == participant_bye
    	  participants = Participant.find(:all, :conditions => ["player_id = ? and active = ?", participant.player_id, true])
    	  participant.player.prestiges = participants.map(&:prestiges).sum
    	  participant.player.game_points = participants.map(&:game_points).sum
    	  participant.player.matches = participants.map(&:matches).sum
        if participant.obtained_bye
          participant.player.matches_with_bye = 0
          participant.player.bye_prestiges = 0
          participant.player.bye_game_points = 0
          participants.each do |p|
            participant.player.matches_with_bye = participant.player.matches_with_bye + 1 if p.obtained_bye == true
            participant.player.bye_prestiges = participant.player.bye_prestiges + p.bye_prestiges
            participant.player.bye_game_points = participant.player.bye_game_points + p.bye_game_points
          end
        end
    	  participant.player.tournaments = participants.count
        participant.player.rating = participant.player.rating + participant.rating_scores
    	  participant.player.save
        participant.results.each do |result|
          competitor_relation = CompetitorRelation.find_or_create_by_player_id_and_competitor_id(result.participant.player_id, result.opponent.player_id)
          competitor_relation.matches = competitor_relation.matches + 1
          competitor_relation.prestiges = competitor_relation.prestiges + result.prestige
          competitor_relation.game_points = competitor_relation.game_points + result.corp_game_points + result.runner_game_points
          competitor_relation.net_rating = competitor_relation.net_rating + result.rating_score
          competitor_relation.save
        end
      end
    end
  end

  private

  def self.activate_or_create(params_player)
    if params_player[:email] and not params_player[:email].blank?
      player = Player.find_by_email params_player[:email], :include => :country
      player.active = true if player
    end
    unless player
      player = Player.new(params_player, :include => :country)
      player.username = player.country.iso + ((Player.count + 90210) * 5 / 2).to_s(16).upcase
    end
    player
  end

  def has_participant?
    true if self.tournament_id
    false unless self.tournament_id
  end

  def create_participant
    Participant.create :player_id => self.id, :tournament_id => self.tournament_id, :rating => self.rating, :name => self.name, :country_id => self.country_id, :place => Participant.find_all_by_tournament_id(self.tournament_id).count
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :authenticate_admin!, :only => [:show, :edit, :update, :destroy]
  # GET /players
  # GET /players.json
  def index
    @players = Player.paginate(:conditions => ["id != ? and active != ?", Var.bye_id, false], :page => params[:page], :per_page => Var.per_page, :include => :country).order('rating DESC')
    @players_json = Player.paginate(:conditions => ["id != ? and active != ?", Var.bye_id, false], :select => 'username, name, prestiges, game_points, matches, tournaments, rating', :page => params[:page], :per_page => 100, :include => :country).order('rating DESC')
    @tournament = Tournament.find params[:tournament] if params[:tournament]
    @rank_counter = (params[:page].to_i - 1) * Var.per_page if params[:page]
    @rank_counter = 0 unless params[:page]
    @participate = true if params[:participant]
    @player = Player.new
    @password = "anr12345"
    # @password = (10000000000000 + rand(89999999999999)).to_s(36)
    @default_email = Var.default_email
    @country_id = Country.malaysia_id

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players_json }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @tournament = Tournament.find params[:tournament] if params[:tournament]
    @participate = true if params[:participant]
    @player = Player.new
    @password = "anr12345"
    # @password = (10000000000000 + rand(89999999999999)).to_s(36)
    @default_email = Var.default_email
    @country_id = Country.malaysia_id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
    @default_email = Var.default_email
    @country_id = @player.country_id
  end

  # POST /players
  # POST /players.json
  def create
    @tournament = Tournament.find params[:player][:tournament_id] if params[:player][:tournament_id]
    @participate = true if @tournament
    @password = params[:player][:password]
    @default_email = Var.default_email
    @country_id = params[:player][:country_id]
    @player = Player.activate_or_create(params[:player]) if Rails.env.development? or organizer_signed_in? or admin_signed_in? or verify_recaptcha(:model => Player.new(params[:player]), :timeout => 3)

    respond_to do |format|
      if @player.save
        Participant.register_player(@player, @tournament.id) if @tournament
        format.html { redirect_to players_url(:tournament => @tournament, :participant => @participate), notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])
    @default_email = Var.default_email
    @country_id = params[:player][:country_id]

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to players_url, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.active = false
    @player.save

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for @player, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @player.errors.any? %>
    <div class="alert alert-block alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="row">
      <div class="span12">
        <div class="control-group">
          <%= f.label :email, :class => 'control-label' %>
          <div class="controls">
            <%= f.email_field :email, :autofocus => true, :class => 'email_field', :placeholder => @default_email %>
            <%= f.hidden_field :tournament_id, value: @tournament.id if @participate %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <div class="control-group">
          <%= f.label :name, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :name, :class => 'text_field' %>
            <%= f.hidden_field :password, value: @password %>
            <%= f.hidden_field :password_confirmation, value: @password %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <div class="control-group">
          <%= f.label :country_id, :class => 'control-label' %>
          <div class="controls">
            <%= f.collection_select :country_id, Country.all, :id, :name, {:selected => @country_id}, {:class => "select"} %>
          </div>
        </div>
      </div>
    </div>
    <% unless organizer_signed_in? or admin_signed_in? or params[:action] == "edit" or params[:action] == "update" %>
      <div class="row">
        <div class="span12">
          <div class="control-group">
            <div class="controls">
              <%= recaptcha_tags :noscript => true %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </fieldset>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary', :onclick => "$(body).addClass('loading');" %>
    <%= link_to 'Cancel', players_path(:tournament => @tournament, :participant => @participate), :class => 'btn' %>
  </div>
<% end %>

app/views/players/edit.html.erb
<div class="page-header">
  <h1>Edit Player Account</h1>
</div>

<%= render 'form' %>

app/views/players/index.html.erb
<div class="page-header">
  <h1>All Players Ranking</h1>
</div>

<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= notice %>
  </div>
<% end %>

<%= will_paginate @players %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Rank</th>
      <th>Rating</th>
      <th>Hacking License</th>
      <th>Name</th>
      <th>Prestiges</th>
      <th>Match Points</th>
      <th>Matches</th>
      <th>Tournaments</th>
    </tr>
  </thead>
  <tbody>
    
    <% @players.each do |player| %>
      <tr>
        <td><%= @rank_counter = @rank_counter + 1 %></td>
        <td><%= player.rating.round %></td>
        <td><%= player.username %></td>
        <td><%= image_tag "countries/" + player.country.iso3 + ".gif", :title => player.country.name, :class => "has-border" %> <%= player.name %></td>
        <td><%= player.prestiges %></td>
        <td><%= player.game_points %></td>
        <td><%= player.matches %></td>
        <td><%= player.tournaments %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @players %>

<%= link_to 'Add a New Player', '#players_new', :class => 'btn btn-primary', :"data-toggle" => 'modal' %>
<%= link_to 'Back to Tournament Page', @tournament, :class => 'btn' if @tournament %>

<div id="players_new" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="label_players_new" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 id="label_players_new">Sign up Player</h3>
  </div>
  <div class="modal-body">
    <%= form_for @player, :html => { :class => 'form-horizontal' } do |f| %>
      <% if @player.errors.any? %>
        <div class="alert alert-block alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

          <ul>
          <% @player.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <fieldset>
        <div class="row">
          <div class="span12">
            <div class="control-group">
              <%= f.label :email, :class => 'control-label' %>
              <div class="controls">
                <%= f.email_field :email, :autofocus => true, :class => 'email_field', :placeholder => @default_email %>
                <%= f.hidden_field :tournament_id, value: @tournament.id if @participate %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="span12">
            <div class="control-group">
              <%= f.label :name, :class => 'control-label' %>
              <div class="controls">
                <%= f.text_field :name, :class => 'text_field' %>
                <%= f.hidden_field :password, value: @password %>
                <%= f.hidden_field :password_confirmation, value: @password %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="span12">
            <div class="control-group">
              <%= f.label :country_id, :class => 'control-label' %>
              <div class="controls">
                <%= f.collection_select :country_id, Country.all, :id, :name, {:selected => @country_id}, {:class => "select"} %>
              </div>
            </div>
          </div>
        </div>
        <% unless organizer_signed_in? or admin_signed_in? or params[:action] == "edit" or params[:action] == "update" %>
          <div class="row">
            <div class="span12">
              <div class="control-group">
                <div class="controls">
                  <%= recaptcha_tags :noscript => true %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </fieldset>
  </div>
  <div class="modal-footer">
      <%= link_to 'Close', '#', :class => 'btn', :"data-dismiss" => 'modal', :"aria-hidden" => true %>
      <%= f.submit nil, :class => 'btn btn-primary', :"data-loading-text" => "Adding Player...", :onclick => "$(this).button('loading').addClass('disabled');" %>
    <% end %>
  </div>
</div>

<br /><br />

app/views/players/new.html.erb
<div class="page-header">
  <h1>Sign up Player</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back to Tournament Page', @tournament, :class => 'btn' if @tournament %>

app/views/players/show.html.erb
<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= notice %>
  </div>
<% end %>

<p>
  <b>Name:</b>
  <%= @player.name %>
</p>

<p>
  <b>Email:</b>
  <%= @player.email %>
</p>

<p>
  <b>Prestiges:</b>
  <%= @player.prestiges %>
</p>

<p>
  <b>Match Points:</b>
  <%= @player.game_points %>
</p>

<p>
  <b>Matches:</b>
  <%= @player.matches %>
</p>

<p>
  <b>Tournaments:</b>
  <%= @player.tournaments %>
</p>

<p>
  <b>Rating:</b>
  <%= @player.rating.round %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>