config/routes.rb
Anr::Application.routes.draw do
  resources :pages, :only => :index
  get 'about_us' => 'pages#about', :as => :about_us
  get 'contact' => 'pages#contact', :as => :contact
  get 'dashboard' => 'tournaments#index', :as => :dashboard
  get 'console' => 'organizers#index', :as => :console
  devise_for :organizers, controllers: { registrations: 'organizers/registrations' }
  devise_for :admins, controllers: { registrations: 'admins/registrations' }

  resources :competitors

  resources :schedules, :only => [:new, :edit, :update]

  resources :rounds, :except => [:index, :create, :destroy]

  resources :participants, :only => [:new, :create, :destroy]

  resources :tournaments

  resources :players

  resources :organizers, :only => [:index, :show]

  root :to => 'pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Android:Netrunner Tournament Console</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= yield(:head) %>
</head>
<body>
<%= nav_bar :inverse => true, :fixed => :top, :brand => image_tag("logo.png", :title => "Android:Netrunner Tournament Console"), :responsive => true do %>
  <%= menu_group do %>
    <%= menu_divider %>
    <%= menu_item "Home", root_path %>
    <%= menu_item "Players Ranking", players_path(:tournament => @tournament) %>
    <%= menu_item "Register Player", new_player_path(:tournament => @tournament, :participant => @participate) %>
    <%= menu_item "About Us", about_us_path %>
    <%= menu_item "Contact", contact_path %>
  <% end %>
  <%= menu_group :pull => :right do %>
    <%= drop_down "Organizer" do %>
      <% if organizer_signed_in? -%>
        <%= menu_item "Tournament Navigator", current_organizer %>
        <%= menu_item "Add a New Tournament", new_tournament_path %>
        <%= drop_down_divider %>
        <%= menu_item "Edit Profile", edit_organizer_registration_path %>
        <%= menu_item "Logout", destroy_organizer_session_path, :method => :delete %>
      <% else -%>
        <%= menu_item "Login", new_organizer_session_path %>
        <%= menu_item "Sign Up", new_organizer_registration_path %>
      <% end -%>
    <% end %>
    <% if admin_signed_in? -%>
      <%= drop_down "Admin" do %>
        <%= menu_item "Dashboard", dashboard_path %>
        <%= menu_item "Console", console_path %>
        <%= drop_down_divider %>
        <%= menu_item "Edit Profile", edit_admin_registration_path %>
        <%= menu_item "Logout", destroy_admin_session_path, :method => :delete %>
      <% end %>
    <% end -%>
  <% end %>
<% end %>
<div class="container">
  <%= yield %>
</div>
<div id="modal">&nbsp;</div>
</body>
</html>